### ISSUE TITLE
Install feedy

### ISSUE THREAD

**Issue by Mingus85** [sungwoncho/feedy#4]
Hi, I just installed feedy as per the instructions. Upon submission, however, the console gives me the following error. What am I doing wrong?
`

> `jquery.self-c64a743….js?body=1:10244 POST https://abc.c9users.io/feedy/feedbacks 500 (Internal Server Error)`

The console:

> ```
> Completed 500 Internal Server Error in 3ms (ActiveRecord: 0.0ms)
> 
> NoMethodError (undefined method `feedbacks' for :current_user:Symbol):
>   feedy (0.0.4) app/controllers/feedy/feedbacks_controller.rb:18:in `create'
> ```

**Comment by sungwoncho** [comment]
I am not maintaining this one actively. So I can't promise to get back on this soon. But please have a look at the working demo. The source code for the demo is available here https://github.com/sungwoncho/feedy.

**Comment by sungwoncho** [comment]
Please reopen if the problem persists in spite of following demo.
